# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0border.proto\x12\x05order\"6\n\x13UpdateStatusRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\",\n\x14UpdateStatusResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"#\n\x10GetStatusRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"4\n\x11GetStatusResponse\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\x97\x01\n\x0cOrderService\x12G\n\x0cUpdateStatus\x12\x1a.order.UpdateStatusRequest\x1a\x1b.order.UpdateStatusResponse\x12>\n\tGetStatus\x12\x17.order.GetStatusRequest\x1a\x18.order.GetStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATESTATUSREQUEST']._serialized_start=22
  _globals['_UPDATESTATUSREQUEST']._serialized_end=76
  _globals['_UPDATESTATUSRESPONSE']._serialized_start=78
  _globals['_UPDATESTATUSRESPONSE']._serialized_end=122
  _globals['_GETSTATUSREQUEST']._serialized_start=124
  _globals['_GETSTATUSREQUEST']._serialized_end=159
  _globals['_GETSTATUSRESPONSE']._serialized_start=161
  _globals['_GETSTATUSRESPONSE']._serialized_end=213
  _globals['_ORDERSERVICE']._serialized_start=216
  _globals['_ORDERSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
