# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kitchen_pb2 as kitchen__pb2


class KitchenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTicket = channel.unary_unary(
                '/kitchen.KitchenService/CreateTicket',
                request_serializer=kitchen__pb2.TicketRequest.SerializeToString,
                response_deserializer=kitchen__pb2.TicketResponse.FromString,
                )
        self.RejectTicket = channel.unary_unary(
                '/kitchen.KitchenService/RejectTicket',
                request_serializer=kitchen__pb2.RejectRequest.SerializeToString,
                response_deserializer=kitchen__pb2.RejectResponse.FromString,
                )


class KitchenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KitchenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTicket,
                    request_deserializer=kitchen__pb2.TicketRequest.FromString,
                    response_serializer=kitchen__pb2.TicketResponse.SerializeToString,
            ),
            'RejectTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectTicket,
                    request_deserializer=kitchen__pb2.RejectRequest.FromString,
                    response_serializer=kitchen__pb2.RejectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kitchen.KitchenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KitchenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kitchen.KitchenService/CreateTicket',
            kitchen__pb2.TicketRequest.SerializeToString,
            kitchen__pb2.TicketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kitchen.KitchenService/RejectTicket',
            kitchen__pb2.RejectRequest.SerializeToString,
            kitchen__pb2.RejectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
