# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kitchen.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkitchen.proto\x12\x07kitchen\" \n\rTicketRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"!\n\x0eTicketResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\rRejectRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"&\n\x0eRejectResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\x92\x01\n\x0eKitchenService\x12?\n\x0c\x43reateTicket\x12\x16.kitchen.TicketRequest\x1a\x17.kitchen.TicketResponse\x12?\n\x0cRejectTicket\x12\x16.kitchen.RejectRequest\x1a\x17.kitchen.RejectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kitchen_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TICKETREQUEST']._serialized_start=26
  _globals['_TICKETREQUEST']._serialized_end=58
  _globals['_TICKETRESPONSE']._serialized_start=60
  _globals['_TICKETRESPONSE']._serialized_end=93
  _globals['_REJECTREQUEST']._serialized_start=95
  _globals['_REJECTREQUEST']._serialized_end=127
  _globals['_REJECTRESPONSE']._serialized_start=129
  _globals['_REJECTRESPONSE']._serialized_end=167
  _globals['_KITCHENSERVICE']._serialized_start=170
  _globals['_KITCHENSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
