# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounting.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x63\x63ounting.proto\x12\naccounting\"3\n\x10\x41uthorizeRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"\'\n\x11\x41uthorizeResponse\x12\x12\n\nauthorized\x18\x01 \x01(\x08\x32\x61\n\x11\x41\x63\x63ountingService\x12L\n\rAuthorizeCard\x12\x1c.accounting.AuthorizeRequest\x1a\x1d.accounting.AuthorizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHORIZEREQUEST']._serialized_start=32
  _globals['_AUTHORIZEREQUEST']._serialized_end=83
  _globals['_AUTHORIZERESPONSE']._serialized_start=85
  _globals['_AUTHORIZERESPONSE']._serialized_end=124
  _globals['_ACCOUNTINGSERVICE']._serialized_start=126
  _globals['_ACCOUNTINGSERVICE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
